/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState, useEffect } from "react";
import { Bell, Zap, Activity, CheckCircle2, AlertTriangle } from "lucide-react";
import { getAlerts } from "@/services/api";
import { SEED_ALERTS } from "@/lib/seed-data";

const severityColors: Record<string, string> = {
  critical: "border-red-200 bg-red-50/60",
  warning: "border-amber-200 bg-amber-50/60",
  info: "border-blue-200 bg-blue-50/60",
};

const severityBadge: Record<string, string> = {
  critical: "bg-red-100 text-red-700 border-red-200",
  warning: "bg-amber-100 text-amber-700 border-amber-200",
  info: "bg-blue-100 text-blue-700 border-blue-200",
};

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<any[]>(SEED_ALERTS);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    getAlerts()
      .then((a) => { if (Array.isArray(a) && a.length > 0) setAlerts(a); })
      .catch(() => {});
  }, []);

  const critical = alerts.filter((a) => a.severity === "critical");
  const warning = alerts.filter((a) => a.severity === "warning");

  return (
    <div className="flex h-full min-h-0 flex-1 flex-col overflow-hidden bg-background">
      <div className="border-b border-border bg-card px-6 py-4">
        <div className="flex items-center gap-3 mb-1">
          <Bell className="size-5 text-emerald-600" />
          <h1 className="text-lg font-bold text-foreground">
            Early Warnings & Alerts
          </h1>
        </div>
        <p className="text-xs text-muted-foreground ml-8">
          Real-time alerts generated by the Early Warning Engine from MO
          clusters, anomalies, and repeat offenders.
        </p>
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        {loading ? (
          <div className="flex h-full items-center justify-center">
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <div className="size-2 rounded-full bg-emerald-500 animate-bounce [animation-delay:0ms]" />
              <div className="size-2 rounded-full bg-emerald-500 animate-bounce [animation-delay:150ms]" />
              <div className="size-2 rounded-full bg-emerald-500 animate-bounce [animation-delay:300ms]" />
              <span className="ml-2">Evaluating alert rules...</span>
            </div>
          </div>
        ) : alerts.length === 0 ? (
          <div className="flex h-full flex-col items-center justify-center text-muted-foreground">
            <CheckCircle2 className="size-12 mb-3 text-emerald-300" />
            <p className="text-sm font-medium text-muted-foreground">
              No Active Alerts
            </p>
            <p className="text-xs mt-1">All systems nominal.</p>
          </div>
        ) : (
          <div className="space-y-4 max-w-3xl">
            {critical.length > 0 && (
              <div>
                <h2 className="text-xs font-bold uppercase tracking-wider text-red-600 flex items-center gap-1.5 mb-3">
                  <Zap className="size-3.5" /> Critical ({critical.length})
                </h2>
                <div className="space-y-2">
                  {critical.map((a: any, i: number) => (
                    <AlertCard key={i} alert={a} />
                  ))}
                </div>
              </div>
            )}
            {warning.length > 0 && (
              <div>
                <h2 className="text-xs font-bold uppercase tracking-wider text-amber-600 flex items-center gap-1.5 mb-3">
                  <AlertTriangle className="size-3.5" /> Warnings (
                  {warning.length})
                </h2>
                <div className="space-y-2">
                  {warning.map((a: any, i: number) => (
                    <AlertCard key={i} alert={a} />
                  ))}
                </div>
              </div>
            )}
            <div>
              <h2 className="text-xs font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5 mb-3">
                <Activity className="size-3.5" /> Other (
                {alerts.length - critical.length - warning.length})
              </h2>
              <div className="space-y-2">
                {alerts
                  .filter(
                    (a) =>
                      a.severity !== "critical" && a.severity !== "warning",
                  )
                  .map((a: any, i: number) => (
                    <AlertCard key={i} alert={a} />
                  ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function AlertCard({ alert }: { alert: any }) {
  const sev = alert.severity || "info";
  return (
    <div
      className={`rounded-2xl border p-4 ${severityColors[sev] || "border-border bg-card"}`}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-2">
          <span
            className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${severityBadge[sev] || "bg-muted text-muted-foreground border-border"}`}
          >
            {sev}
          </span>
          <span className="text-xs font-bold text-foreground">
            {alert.title}
          </span>
        </div>
        <span className="text-[10px] text-muted-foreground shrink-0">
          {alert.timestamp
            ? new Date(alert.timestamp).toLocaleDateString()
            : "Just now"}
        </span>
      </div>
      <p className="mt-2 text-xs text-muted-foreground leading-relaxed">
        {alert.description}
      </p>
      {alert.data && (
        <pre className="mt-2 text-[10px] text-muted-foreground bg-muted p-2 rounded-lg border border-border overflow-x-auto max-h-20">
          {JSON.stringify(alert.data, null, 1)}
        </pre>
      )}
      <div className="mt-2 flex items-center gap-2">
        <span className="text-[10px] font-medium text-muted-foreground">
          {alert.type || "system"}
        </span>
        {!alert.acknowledged && (
          <span className="text-[10px] font-semibold text-emerald-600 flex items-center gap-1">
            <span className="size-1.5 rounded-full bg-emerald-500 animate-pulse" />{" "}
            Active
          </span>
        )}
      </div>
    </div>
  );
}
