"use client";

import {
  ArrowRight,
  ChevronDown,
  Globe2,
  Network,
  FileSearch,
  Map,
  Shield,
  Brain,
  CheckCircle2,
  ArrowUpRight,
  BarChart3,
  MessageSquareText,
  Eye,
  Zap,
  GraduationCap,
} from "lucide-react";
import { motion, type Variants } from "motion/react";

const sectionVariants: Variants = {
  hidden: {},
  visible: {
    transition: { staggerChildren: 0.13, delayChildren: 0.08 },
  },
};

const navWrapVariants: Variants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.07 } },
};

const navItemVariants: Variants = {
  hidden: { opacity: 0, y: -16, filter: "blur(6px)" },
  visible: {
    opacity: 1,
    y: 0,
    filter: "blur(0px)",
    transition: { type: "spring", duration: 0.55, bounce: 0.2 },
  },
};

const bgVariants: Variants = {
  hidden: { opacity: 0, scale: 1.1, filter: "blur(24px)" },
  visible: {
    opacity: 1,
    scale: 1,
    filter: "blur(0px)",
    transition: { duration: 1.6, ease: [0.16, 1, 0.3, 1] },
  },
};

const glowVariants: Variants = {
  hidden: { opacity: 0, scale: 0.4 },
  visible: {
    opacity: [0, 0.55, 0.35],
    scale: [0.4, 1.15, 1],
    transition: { duration: 1.8, ease: "easeOut", times: [0, 0.6, 1] },
  },
};

const descVariants: Variants = {
  hidden: { opacity: 0, y: 22, filter: "blur(10px)" },
  visible: {
    opacity: 1,
    y: 0,
    filter: "blur(0px)",
    transition: { type: "spring", duration: 0.8, bounce: 0 },
  },
};

const ctaVariants: Variants = {
  hidden: { opacity: 0, scale: 0.82, filter: "blur(8px)" },
  visible: {
    opacity: 1,
    scale: 1,
    filter: "blur(0px)",
    transition: { type: "spring", duration: 0.7, bounce: 0.3 },
  },
};

const trustVariants: Variants = {
  hidden: { opacity: 0, rotateX: 90, y: 20 },
  visible: {
    opacity: 1,
    rotateX: 0,
    y: 0,
    transition: { type: "spring", duration: 0.8, bounce: 0.15, delay: 0.2 },
  },
};

const charContainerVariants: Variants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.03, delayChildren: 0 } },
};

const charVariants: Variants = {
  hidden: { opacity: 0, y: 40, rotateZ: -8, filter: "blur(8px)" },
  visible: {
    opacity: 1,
    y: 0,
    rotateZ: 0,
    filter: "blur(0px)",
    transition: { type: "spring", duration: 0.55, bounce: 0.25 },
  },
};

const fadeUpVariants: Variants = {
  hidden: { opacity: 0, y: 40, filter: "blur(8px)" },
  visible: {
    opacity: 1,
    y: 0,
    filter: "blur(0px)",
    transition: { type: "spring", duration: 0.7, bounce: 0.15 },
  },
};

const featureCardVariants: Variants = {
  hidden: { opacity: 0, y: 50, filter: "blur(10px)" },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    filter: "blur(0px)",
    transition: {
      type: "spring",
      duration: 0.7,
      bounce: 0.12,
      delay: 0.08 * i,
    },
  }),
};

const stepVariants: Variants = {
  hidden: { opacity: 0, x: -30, filter: "blur(8px)" },
  visible: (i: number) => ({
    opacity: 1,
    x: 0,
    filter: "blur(0px)",
    transition: { type: "spring", duration: 0.6, bounce: 0.1, delay: 0.12 * i },
  }),
};

function DropCharsLine({
  text,
  className,
}: {
  text: string;
  className?: string;
}) {
  return (
    <motion.span
      className={`block overflow-visible ${className ?? ""}`}
      variants={charContainerVariants}
    >
      {text.split("").map((ch, i) => (
        <motion.span
          key={i}
          className="inline-block will-change-transform"
          variants={charVariants}
          style={{ whiteSpace: ch === " " ? "pre" : undefined }}
        >
          {ch === " " ? "\u00a0" : ch}
        </motion.span>
      ))}
    </motion.span>
  );
}

const engines = [
  {
    icon: Brain,
    title: "Crime DNA Engine",
    tag: "KILLER FEATURE",
    description:
      "When a new FIR arrives, the system automatically extracts its MO signature, matches against years of history, updates criminal networks, and generates early warnings — all in one real-time cascade.",
    features: [
      "MO feature extraction & vector building",
      "Cosine similarity + geographic proximity search",
      "Automatic pattern & early warning detection",
    ],
  },
  {
    icon: MessageSquareText,
    title: "GraphRAG Intelligence",
    tag: "CONVERSATIONAL",
    description:
      "Ask questions in English or Kannada-English code-mix. Every answer is generated by traversing the Knowledge Graph — not by hallucination. Each result cites its exact source nodes and edges.",
    features: [
      "Schema-grounded Cypher query planning",
      "Hybrid graph + vector retrieval",
      "Cited, court-defensible responses",
    ],
  },
  {
    icon: Network,
    title: "Network Analysis",
    tag: "CRIMINAL INTELLIGENCE",
    description:
      "Surfaces organized crime structures, repeat offender networks, and hidden associations. Community detection reveals gangs that no single FIR could expose.",
    features: [
      "Louvain community detection algorithms",
      "Centrality analysis (PageRank, betweenness)",
      "Hidden link prediction & visualization",
    ],
  },
  {
    icon: Map,
    title: "Forecasting & Early Warning",
    tag: "PREDICTIVE",
    description:
      "Predicts crime hotspots using spatio-temporal models and generates early warnings for emerging crime patterns. Every forecast includes confidence intervals and backtest accuracy.",
    features: [
      "KDE grid-based hotspot probability mapping",
      "Prophet-style temporal forecasting",
      "Rule-based + anomaly trigger hybrid warnings",
    ],
  },
  {
    icon: FileSearch,
    title: "Investigation Support",
    tag: "SIMILAR CASES",
    description:
      "Automatically finds similar past cases with their outcomes and suggests investigative leads. Converts the department's entire case history into reusable institutional intelligence.",
    features: [
      "Sentence-BERT narrative similarity search",
      "MO feature + entity overlap re-ranking",
      "Outcome-linked technique recommendations",
    ],
  },
];

const steps = [
  {
    number: "01",
    icon: Upload,
    title: "Ingest",
    description:
      "Upload an FIR — PDF, form entry, or API. Entity extraction immediately identifies accused, victims, locations, and MO details.",
  },
  {
    number: "02",
    icon: BarChart3,
    title: "Analyze",
    description:
      "Five intelligence engines process the data in parallel — Crime DNA matching, network expansion, pattern detection, forecasting update, and similar case retrieval.",
  },
  {
    number: "03",
    icon: Eye,
    title: "Act",
    description:
      "Get an intelligence report with cited sources, confidence scores, and actionable leads. Everything is court-defensible and audit-logged.",
  },
];

function Upload({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" y1="3" x2="12" y2="15" />
    </svg>
  );
}

export default function LandingPage() {
  return (
    <div className="font-sans antialiased">
      {/* ===== HERO ===== */}
      <section className="relative isolate min-h-screen overflow-hidden bg-stone-100 text-emerald-950">
        <motion.div
          className="relative flex min-h-screen w-full flex-col overflow-hidden px-7 py-4 sm:px-11 lg:px-14"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.25 }}
          variants={sectionVariants}
        >
          <motion.img
            variants={bgVariants}
            src="https://assets.watermelon.sh/hero-20-bg.avif"
            alt=""
            className="pointer-events-none absolute inset-0 h-full w-full object-cover"
          />

          <motion.div
            variants={glowVariants}
            aria-hidden
            className="pointer-events-none absolute left-1/2 top-1/2 z-0 -translate-x-1/2 -translate-y-1/2 h-[70vmin] w-[70vmin] rounded-full bg-emerald-400/30 blur-[80px]"
          />

          <motion.nav
            variants={navWrapVariants}
            className="relative z-20 flex min-h-10 w-full items-center justify-between"
          >
            <motion.a
              variants={navItemVariants}
              href="#"
              className="inline-flex min-h-10 items-center gap-2 text-lg leading-none font-medium tracking-[-0.035em] text-emerald-950 transition-[opacity,transform] duration-200 ease-out hover:opacity-80 active:scale-[0.96]"
            >
              KCI-OS
            </motion.a>

            <div className="hidden items-center gap-[3.1rem] lg:flex">
              {["Platform", "Capabilities", "Architecture", "Contact"].map(
                (label) => (
                  <motion.a
                    key={label}
                    variants={navItemVariants}
                    href={`#${label.toLowerCase()}`}
                    className="inline-flex min-h-10 items-center text-sm font-medium text-emerald-950/90 transition-[opacity,transform] duration-200 ease-out hover:opacity-90 active:scale-[0.96]"
                  >
                    {label}
                  </motion.a>
                ),
              )}
            </div>

            <div className="flex items-center gap-4">
              <motion.button
                variants={navItemVariants}
                type="button"
                className="hidden min-h-10 items-center gap-1.5 text-sm font-medium text-emerald-950 transition-[opacity,transform] duration-200 ease-out hover:opacity-90 active:scale-[0.96] sm:inline-flex"
              >
                <Globe2 className="size-4" aria-hidden="true" />
                EN
                <ChevronDown className="size-4" aria-hidden="true" />
              </motion.button>
              <motion.a
                variants={navItemVariants}
                href="/dashboard"
                className="group inline-flex min-h-10 items-center justify-center gap-2 rounded-sm bg-emerald-900 px-5 text-sm font-medium text-amber-50 shadow-[inset_0_1px_4px_2px_rgba(255,255,255,0.2),inset_0_-1px_4px_2px_rgba(0,0,0,0.2)] transition-[background-color,transform,box-shadow] duration-200 ease-out hover:bg-emerald-950 active:scale-[0.96]"
              >
                Open Dashboard
                <ArrowRight className="size-4 transition-transform duration-200 ease-out group-hover:translate-x-0.5" />
              </motion.a>
            </div>
          </motion.nav>

          <div className="relative z-10 flex flex-1 flex-col justify-center pt-16 pb-32 sm:pt-20 md:pb-36 lg:pt-10">
            <div className="max-w-5xl">
              <h1 className="max-w-5xl text-[clamp(3.25rem,5.4vw,5.15rem)] leading-[0.94] font-normal tracking-[-0.065em] text-emerald-900">
                <DropCharsLine text="Intelligence That" />
                <DropCharsLine text="Protects Karnataka" />
              </h1>

              <motion.p
                variants={descVariants}
                className="mt-5 max-w-lg text-md leading-[1.12] font-medium text-pretty text-emerald-950/80"
              >
                An AI-powered crime intelligence platform enabling
                investigators, analysts, and policymakers to query Karnataka's
                crime database using natural language - uncovering hidden
                patterns, predicting hotspots, and strengthening proactive law
                enforcement.
              </motion.p>

              <motion.div
                variants={ctaVariants}
                className="mt-6 flex items-center gap-4"
              >
                <a
                  href="/dashboard"
                  className="group inline-flex min-h-10 items-center border-b border-emerald-950 pb-1 text-md font-medium tracking-[-0.035em] text-emerald-950 transition-[opacity,transform] duration-200 ease-out hover:opacity-75 active:scale-[0.96]"
                >
                  Launch Demo
                  <ArrowRight className="ml-1 size-4 -rotate-45 transition-transform duration-200 ease-out group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
                </a>
                <a
                  href="#capabilities"
                  className="group inline-flex min-h-10 items-center gap-1.5 text-sm font-medium text-emerald-950/60 transition-[opacity,transform] duration-200 ease-out hover:text-emerald-950 active:scale-[0.96]"
                >
                  Explore Capabilities
                  <ChevronDown className="size-3.5" />
                </a>
              </motion.div>
            </div>
          </div>

          <motion.p
            variants={trustVariants}
            style={{ perspective: 600 }}
            className="absolute right-7 bottom-9 z-20 hidden max-w-48 text-left text-sm leading-wide font-normal text-white/80 drop-shadow-[0_2px_12px_rgba(6,78,59,0.3)] sm:block sm:right-11 md:text-right lg:right-14"
          >
            Built for Karnataka
            <br />
            State Police
          </motion.p>
        </motion.div>
      </section>

      {/* ===== PLATFORM OVERVIEW ===== */}
      <section
        id="platform"
        className="bg-stone-100 px-7 py-24 sm:px-11 lg:px-14"
      >
        <div className="mx-auto max-w-7xl">
          <motion.div
            className="mx-auto max-w-3xl text-center"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >
            <motion.h2
              variants={fadeUpVariants}
              className="text-3xl leading-[1.1] font-normal tracking-[-0.045em] text-emerald-900 sm:text-4xl lg:text-5xl"
            >
              Not a Chatbot.
              <br />
              <span className="text-emerald-700">
                A Crime Intelligence Operating System.
              </span>
            </motion.h2>
            <motion.p
              variants={fadeUpVariants}
              className="mt-5 text-sm leading-relaxed text-emerald-800/70"
            >
              Most teams build a chatbot with analytics. KCI-OS is a full
              intelligence platform where the chatbot is just the front door.
              Behind it sits a Knowledge Graph that every engine reads from,
              five intelligence engines that proactively generate insights, and
              a governance layer that makes every answer court-defensible.
            </motion.p>
          </motion.div>

          <motion.div
            className="mt-16 grid gap-6 sm:grid-cols-3"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.2 }}
          >
            {[
              {
                icon: Zap,
                title: "Event-Driven Intelligence",
                desc: "When a new FIR arrives, the entire system ripples — graph updates, risk scores re-calculate, early warnings fire. Intelligence is proactive, not reactive.",
              },
              {
                icon: GraduationCap,
                title: "Bilingual by Default",
                desc: "English, Kannada, and code-mixed queries work natively. No translation wrapper — real multilingual NLU built for Karnataka's officers.",
              },
              {
                icon: Shield,
                title: "Court-Defensible Governance",
                desc: "Every answer cites its source nodes and edges with confidence scores. Fact vs Hypothesis toggle. Audit-logged, immutable, and role-scoped.",
              },
            ].map((item, i) => (
              <motion.div
                key={item.title}
                custom={i}
                variants={featureCardVariants}
                className="group rounded-xl border border-emerald-900/10 bg-white/60 p-6 transition-all duration-300 hover:border-emerald-900/20 hover:bg-white/80 hover:shadow-sm"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-900/10 text-emerald-700 transition-colors duration-300 group-hover:bg-emerald-900/15">
                  <item.icon className="size-5" />
                </div>
                <h3 className="mt-4 text-base font-medium text-emerald-900">
                  {item.title}
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-emerald-800/60">
                  {item.desc}
                </p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ===== FIVE CORE ENGINES ===== */}
      <section
        id="capabilities"
        className="bg-emerald-950 px-7 py-24 sm:px-11 lg:px-14"
      >
        <div className="mx-auto max-w-7xl">
          <motion.div
            className="mx-auto max-w-3xl text-center"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >
            <motion.h2
              variants={fadeUpVariants}
              className="text-3xl leading-[1.1] font-normal tracking-[-0.045em] text-emerald-50 sm:text-4xl lg:text-5xl"
            >
              Built on{" "}
              <span className="text-emerald-400">Five Core Engines</span>
            </motion.h2>
            <motion.p
              variants={fadeUpVariants}
              className="mt-5 text-sm leading-relaxed text-emerald-300/60"
            >
              Not 9 features done poorly — 5 engines done exceptionally well.
              Every engine is designed to work independently and together,
              creating intelligence that no single tool could produce.
            </motion.p>
          </motion.div>

          <div className="mt-16 space-y-6">
            {engines.map((engine, i) => (
              <motion.div
                key={engine.title}
                custom={i}
                variants={featureCardVariants}
                className="group relative overflow-hidden rounded-xl border border-emerald-800/30 bg-emerald-900/20 p-6 transition-all duration-300 hover:border-emerald-700/40 hover:bg-emerald-900/30 sm:p-8"
              >
                <div className="flex flex-col gap-6 lg:flex-row lg:items-start">
                  <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-emerald-400/10 text-emerald-400">
                    <engine.icon className="size-6" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-3">
                      <h3 className="text-lg font-medium text-emerald-50">
                        {engine.title}
                      </h3>
                      <span className="rounded-full bg-emerald-400/10 px-2.5 py-0.5 text-[10px] font-medium tracking-wider text-emerald-400">
                        {engine.tag}
                      </span>
                    </div>
                    <p className="mt-2 max-w-2xl text-sm leading-relaxed text-emerald-300/60">
                      {engine.description}
                    </p>
                    <ul className="mt-4 flex flex-wrap gap-x-6 gap-y-2">
                      {engine.features.map((f) => (
                        <li
                          key={f}
                          className="flex items-center gap-1.5 text-xs text-emerald-300/50"
                        >
                          <CheckCircle2 className="size-3 text-emerald-400/60" />
                          {f}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div className="hidden shrink-0 self-center lg:block">
                    <div className="flex h-10 w-10 items-center justify-center rounded-full border border-emerald-700/30 text-emerald-500/50 transition-all duration-300 group-hover:border-emerald-500/40 group-hover:text-emerald-400">
                      <ArrowUpRight className="size-4" />
                    </div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== HOW IT WORKS ===== */}
      <section className="bg-stone-100 px-7 py-24 sm:px-11 lg:px-14">
        <div className="mx-auto max-w-7xl">
          <motion.div
            className="mx-auto max-w-3xl text-center"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >
            <motion.h2
              variants={fadeUpVariants}
              className="text-3xl leading-[1.1] font-normal tracking-[-0.045em] text-emerald-900 sm:text-4xl lg:text-5xl"
            >
              How It Works
            </motion.h2>
            <motion.p
              variants={fadeUpVariants}
              className="mt-5 text-sm leading-relaxed text-emerald-800/70"
            >
              Three steps transform a standard FIR into actionable criminal
              intelligence.
            </motion.p>
          </motion.div>

          <div className="mt-16 grid gap-8 md:grid-cols-3">
            {steps.map((step, i) => (
              <motion.div
                key={step.number}
                custom={i}
                variants={stepVariants}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.3 }}
                className="relative"
              >
                <div className="flex items-center gap-4">
                  <span className="text-5xl leading-none font-light tracking-[-0.08em] text-emerald-900/10">
                    {step.number}
                  </span>
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-900/10 text-emerald-700">
                    <step.icon className="size-5" />
                  </div>
                </div>
                <h3 className="mt-4 text-lg font-medium text-emerald-900">
                  {step.title}
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-emerald-800/60">
                  {step.description}
                </p>
                {i < steps.length - 1 && (
                  <div className="absolute top-6 left-17 hidden h-px w-[calc(100%-5rem)] bg-emerald-900/10 md:block" />
                )}
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== WHY KCI-OS ===== */}
      <section
        id="architecture"
        className="bg-emerald-950 px-7 py-24 sm:px-11 lg:px-14"
      >
        <div className="mx-auto max-w-7xl">
          <motion.div
            className="mx-auto max-w-3xl text-center"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >

            <motion.h2
              variants={fadeUpVariants}
              className="text-3xl leading-[1.1] font-normal tracking-[-0.045em] text-emerald-50 sm:text-4xl lg:text-5xl"
            >
              Beyond the{" "}
              <span className="text-emerald-400">Standard Dashboard</span>
            </motion.h2>
          </motion.div>

          <motion.div
            className="mt-16 grid gap-4 sm:grid-cols-2"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.2 }}
          >
            {[
              {
                label: "Query Interface",
                us: "Conversational AI with multi-hop GraphRAG",
                them: "Search bar or dropdown filters",
              },
              {
                label: "Network Analysis",
                us: "Community detection + centrality + link prediction",
                them: "Force-directed graph, no analysis",
              },
              {
                label: "Crime Forecasting",
                us: "KDE + Prophet model with backtest accuracy",
                them: "Static heatmap labeled 'prediction'",
              },
              {
                label: "Language Support",
                us: "Code-mixed Kannada-English NLU",
                them: "English-only with translation API",
              },
              {
                label: "Explainability",
                us: "Every answer cites nodes, edges, confidence scores",
                them: "AI answers with no traceability",
              },
              {
                label: "Data Strategy",
                us: "Messy synthetic data + live entity resolution",
                them: "Clean demo data, no real-world testing",
              },
              {
                label: "Intelligence Model",
                us: "Event-driven proactive intelligence cascade",
                them: "Reactive query-response only",
              },
              {
                label: "Court Readiness",
                us: "Fact/Hypothesis toggle, audit log, RBAC",
                them: "No governance or compliance features",
              },
            ].map((row, i) => (
              <motion.div
                key={row.label}
                custom={i}
                variants={featureCardVariants}
                className="rounded-xl border border-emerald-800/20 bg-emerald-900/10 p-5"
              >
                <p className="text-xs font-medium tracking-wider text-emerald-400/60">
                  {row.label}
                </p>
                <div className="mt-3 grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-xs text-emerald-300/40">KCI-OS</p>
                    <p className="mt-1 text-sm leading-snug text-emerald-100">
                      {row.us}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs text-emerald-300/40">
                      Typical Approach
                    </p>
                    <p className="mt-1 text-sm leading-snug text-emerald-300/40">
                      {row.them}
                    </p>
                  </div>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ===== CTA ===== */}
      <section
        id="contact"
        className="relative overflow-hidden  px-7 py-24 sm:px-11 lg:px-14"
      >
        <div className="pointer-events-none absolute -right-40 -top-40 h-96 w-96 rounded-full bg-emerald-500/10 blur-[120px]" />
        <div className="pointer-events-none absolute -bottom-40 -left-40 h-96 w-96 rounded-full bg-emerald-400/10 blur-[120px]" />

        <motion.div
          className="relative mx-auto max-w-3xl text-center"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.3 }}
        >
          <motion.h2
            variants={fadeUpVariants}
            className="text-3xl leading-[1.1] font-normal tracking-[-0.045em] text-black sm:text-4xl lg:text-5xl"
          >
            From FIR to Intelligence
            <br />
            <span className="text-emerald-300">in 60 Seconds.</span>
          </motion.h2>
          <motion.p
            variants={fadeUpVariants}
            className="mt-5 text-sm leading-relaxed text-black"
          >
            See how KCI-OS transforms the way Karnataka State Police
            investigates crime. Upload an FIR and watch the entire system
            respond in real time.
          </motion.p>
          <motion.div
            variants={ctaVariants}
            className="mt-8 flex items-center justify-center gap-4"
          >
            <a
              href="/dashboard"
              className="group inline-flex min-h-10 items-center gap-2 rounded-sm bg-amber-50 px-6 text-sm font-medium text-emerald-950 shadow-[inset_0_1px_4px_2px_rgba(255,255,255,0.3),inset_0_-1px_4px_2px_rgba(0,0,0,0.15)] transition-all duration-200 ease-out hover:bg-white hover:shadow-[inset_0_1px_4px_2px_rgba(255,255,255,0.4),inset_0_-1px_4px_2px_rgba(0,0,0,0.2)] active:scale-[0.96]"
            >
              Launch Live Demo
              <ArrowRight className="size-4 transition-transform duration-200 ease-out group-hover:translate-x-0.5" />
            </a>
          </motion.div>
        </motion.div>
      </section>

      {/* ===== FOOTER ===== */}
      <footer className="border-t border-emerald-900/10 bg-emerald-950 px-7 py-12 sm:px-11 lg:px-14">
        <div className="mx-auto max-w-7xl">
          <div className="flex flex-col items-center justify-between gap-6 md:flex-row">
            <div className="flex items-center gap-2 text-sm font-medium text-emerald-300/50">
              <Shield className="size-4" />
              KCI-OS — Karnataka Crime Intelligence Operating System
            </div>
            <div className="flex items-center gap-6 text-xs text-emerald-400/30">
              <a
                href="#"
                className="transition-colors hover:text-emerald-300/50"
              >
                Privacy
              </a>
              <a
                href="#"
                className="transition-colors hover:text-emerald-300/50"
              >
                Terms
              </a>
              <a
                href="#"
                className="transition-colors hover:text-emerald-300/50"
              >
                Documentation
              </a>
              <span>KSP Datathon 2026</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
